export const types = {
	AUTH_USERINFO: "SeaCat/AUTH_USERINFO",
	AUTH_RESOURCES: "SeaCat/AUTH_RESOURCES",
	NAVIGATION_UNAUTHORIZED_ITEM: "SeaCat/Navigation/UNAUTHORIZED_ITEM",
	NAVIGATION_UNAUTHORIZED_CHILDREN: "SeaCat/Navigation/UNAUTHORIZED_CHILDREN",
}
